[tox]
envlist = py310, py311, py312, py313, docs
skipsdist = true

[testenv:docs]
basepython=python
changedir=docs
deps=sphinx
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pip install -U pip
    pytest
