[tox]
skipsdist = True
envlist = py310, py311, py312, py313, ruff

[testenv:ruff]
basepython = python
deps = ruff
commands = ruff check src tests

[testenv]
allowlist_externals = poetry
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}
{% if cookiecutter.use_pytest == "y" -%}
deps = pytest-cov
; Use poetry to install dependencies into each tox environment.
commands =
    poetry install --with dev -v
    poetry run pytest --cov=src/{{ cookiecutter.project_slug }} tests/
{% else %}
commands = poetry run python -m test
{%- endif %}
